const images = {
  ellipse_1: require('./exemplos/Ellipse 1.png'),
  ellipse_2: require('./exemplos/Ellipse 2.png'),
  ellipse_3: require('./exemplos/Ellipse 3.png'),
  ellipse_4: require('./exemplos/Ellipse 4.png'),
  ellipse_5: require('./exemplos/Ellipse 5.png'),
  produto_dove: require('./exemplos/produto-dove.png'),
  produto_fralda: require('./exemplos/produto-fralda.png'),
  servico1: require('./exemplos/servico1.png'),
  servico2: require('./exemplos/servico2.png'),
  bell: require('./icons/bell.png'),
  box: require('./icons/box.png'),
  credit_card: require('./icons/credit_card.png'),
  cupon: require('./icons/cupon.png'),
  fast: require('./icons/fast.png'),
  health_metrics: require('./icons/health_metrics.png'),
  home: require('./icons/home.png'),
  loyalty: require('./icons/loyalty.png'),
  package: require('./icons/package.png'),
  profile: require('./icons/profile.png'),
  search: require('./icons/search.png'),
  service: require('./icons/service.png'),
  shopping_cart: require('./icons/shopping-cart.png'),
  truck: require('./icons/truck.png'),
  compre_online: require('./juquinha/compre online.png'),
  juquinha_direita: require('./juquinha/JUQUINHA direita.png'),
  juquinha_esquerda: require('./juquinha/JUQUINHA esquerda.png'),
  juquinha_frente: require('./juquinha/JUQUINHA frente.png'),
  logo_azul_transparente: require('./logo/logo azul transparente.png'),
  logo_branca_fundo_transparente: require('./logo/logo branca fundo transparente.png'),
  logo_extensa_azul_fundo_branco: require('./logo/logo extensa azul fundo branco.jpg'),
  logo_extensa_azul_fundo_transparente: require('./logo/Logo extensa azul fundo transparente.png'),
  logo_extensa_branca_fundo_azul: require('./logo/logo extensa branca FUNDO AZUL.png'),
  logo_transparente: require('./logo/logo transparente.png'),
  header: require('./outros/header.jpg'),
  plano_de_fundo_drogaria: require('./PLANO DE FUNDO DROGARIA.jpg'),
  adaptive_icon: require('./react-native/adaptive-icon.png'),
  favicon: require('./react-native/favicon.png'),
  icon: require('./react-native/icon.png'),
  splash_icon: require('./react-native/splash-icon.png'),
} as const;

type Images = keyof typeof images;

export { images };
export type { Images };
